### ISSUE TITLE
update must specify both set and unset

### ISSUE THREAD

**Issue by zankia** [remyla/damas-core#100] opened 2016-04-12 15:43 UTC
To call damas.update(),  keys to set AND keys to unset must be specified in the parameter keys.

For example, to modify a single key, we have to set a null field into the keys object.
```javascript
damas.update(id, {field:value, a:null});
```

This is because MongoDB refuses to update if $set or $unset is set but empty

The error is the following : 
```
app:model:mongo:15079 err: +1ms { name: 'MongoError',
  code: 9,
  errmsg: '\'$unset\' is empty. You must specify a field like so: {$mod: {<field>: ...}}' }
```

**Comment by remyla** [comment] 2016-04-18 08:38
Thanks for this issue. I can't reproduce the error you mention. Here is my Mongo version and the procedure, if I understood well, that could reproduce the bug. Else, please give me the procedure to reproduce.

```sh
$ mongo
MongoDB shell version: 2.4.14
connecting to: test
```
I give an empty object {} to $unset
```js
> use test
> db.test.insert({cle1:"val1", cle2:"val2"})
> db.test.find()
{ "_id" : ObjectId("5714997e373fc4aed8755d9c"), "cle1" : "val1", "cle2" : "val2" }
> db.test.update({},{$set:{cle3:"val3"},$unset:{}})
> db.test.find()
{ "_id" : ObjectId("5714997e373fc4aed8755d9c"), "cle1" : "val1", "cle2" : "val2", "cle3" : "val3" }
```
or to $set:
```
> db.test.update({},{$set:{},$unset:{cle3:true}})
> db.test.find()
{ "_id" : ObjectId("5714997e373fc4aed8755d9c"), "cle1" : "val1", "cle2" : "val2" }
```

what is your version of MongoDB?

**Comment by zankia** [comment] 2016-04-18 09:09
I am running MongoDB 2.6.10

Here is what I have :

``` javascript
> use test
switched to db test
> db.test.insert({cle1:"val1", cle2:"val2"})
WriteResult({ "nInserted" : 1 })
> db.test.find()
{ "_id" : ObjectId("5714a3171a0e359f87997e59"), "cle1" : "val1", "cle2" : "val2" }
> db.test.update({},{$set:{cle3:"val3"},$unset:{}})
WriteResult({
	"nMatched" : 0,
	"nUpserted" : 0,
	"nModified" : 0,
	"writeError" : {
		"code" : 9,
		"errmsg" : "'$unset' is empty. You must specify a field like so: {$mod: {<field>: ...}}"
	}
})
```

**Comment by zankia** [comment] 2016-04-18 09:16
This is due to the [version incompability](https://docs.mongodb.org/manual/release-notes/2.6-compatibility/#update-operations-incompatibility).

**Comment by remyla** [comment] 2016-04-18 10:12
thanks, pull request #103 merged in testing, i close this issue

**Closed by remyla** 2016-04-18 10:12 UTC
